events {}
http {
    server {
        listen 5601;

        location /api/status {
            add_header kbn-name "kibana-lab";
            default_type application/json;
            return 200 '{"name":"kibana-lab","status":{"overall":{"state":"green","title":"Green","nickname":"Looking good","icon":"success","uiColor":"secondary"},"statuses":[{"id":"core:savedObjects","message":"Ready","state":"green"}]},"version":{"number":"7.17.18","build_hash":"abc123def456","build_number":50000}}';
        }
    }
}
