[global]
   workgroup = WORKGROUP
   server string = ServiceGuard Samba Lab
   security = user
   map to guest = Bad User
   guest account = nobody
   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes

[public]
   comment = Public Unauthenticated Share
   path = /shares/public
   browseable = yes
   read only = no
   guest ok = yes
   guest only = yes
