events {}
http {
    server {
        listen 2375;
        location /_ping {
            add_header Content-Type text/plain;
            return 200 'OK';
        }
        location /version {
            add_header Content-Type application/json;
            return 200 '{"Platform":{"Name":"Docker Engine - Community"},"Components":[{"Name":"Engine","Version":"25.0.3"}],"Version":"25.0.3","ApiVersion":"1.44","MinAPIVersion":"1.24","GitCommit":"4debf41","GoVersion":"go1.21.6","Os":"linux","Arch":"amd64"}';
        }
        location /containers/json {
            add_header Content-Type application/json;
            return 200 '[]';
        }
    }
}
