events {}
http {
    server {
        listen 6443 ssl;
        listen 8443;

        ssl_certificate /etc/nginx/cert.pem;
        ssl_certificate_key /etc/nginx/key.pem;

        location /version {
            default_type application/json;
            return 200 '{"major":"1","minor":"28","gitVersion":"v1.28.2","gitCommit":"89a4ea39044a89b6bb1724134e6210b80038d03","gitTreeState":"clean","buildDate":"2023-09-13T09:28:44Z","goVersion":"go1.20.8","compiler":"gc","platform":"linux/amd64"}';
        }

        location /api/v1/namespaces {
            default_type application/json;
            return 200 '{"kind":"NamespaceList","apiVersion":"v1","metadata":{"resourceVersion":"1024"},"items":[{"metadata":{"name":"default"}},{"metadata":{"name":"kube-system"}},{"metadata":{"name":"kube-public"}}]}';
        }

        location /api/v1/pods {
            default_type application/json;
            return 200 '{"kind":"PodList","apiVersion":"v1","metadata":{"resourceVersion":"1024"},"items":[{"metadata":{"name":"core-service-1","namespace":"default"}}]}';
        }
    }
}
