events {}
http {
    server {
        listen 9870;

        location /webhdfs/v1/ {
            default_type application/json;
            return 200 '{"FileStatuses":{"FileStatus":[{"accessTime":1694000000000,"blockSize":134217728,"childrenNum":0,"fileId":16386,"group":"supergroup","length":0,"modificationTime":1694000000000,"owner":"hdfs","pathSuffix":"user","permission":"755","replication":0,"storagePolicy":0,"type":"DIRECTORY"}]}}';
        }
    }
}
